In [100]:
import numpy as np
import pandas as pd


In [101]:
df= pd.read_csv("/kaggle/input/sms-spam-collection-dataset/spam.csv", encoding= 'ISO-8859-1', encoding_errors = 'strict')

In [102]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [103]:
# cleaning this dataset

df=df.drop(df.columns[[2,3,4]], axis=1)

In [104]:
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [105]:

# Renaming multiple columns
df.rename(columns={'v1': 'Label', 'v2': 'Text'}, inplace=True)


In [106]:
df.head()

Label                                               Text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [107]:
df.Text[0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [108]:
# Apply the regular expression to the "Text" column and join the results with a space
df['Text'] = df['Text'].apply(lambda x: ' '.join(re.findall(r'[A-Za-z0-9]+', str(x))))


In [109]:
df['Text'][0]

'Go until jurong point crazy Available only in bugis n great world la e buffet Cine there got amore wat'

In [110]:
df.Label=df.Label.apply(lambda x: 1 if x=="spam" else 0)

In [111]:
df.head()

Label                                               Text
0      0  Go until jurong point crazy Available only in ...
1      0                            Ok lar Joking wif u oni
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0        U dun say so early hor U c already then say
4      0  Nah I don t think he goes to usf he lives arou...

In [112]:
from sklearn.model_selection import train_test_split

In [113]:
X_train, X_test, y_train, y_test=train_test_split(df.Text, df.Label, test_size=0.2)

In [114]:
X_train.shape

(4457,)

In [115]:
from sklearn.feature_extraction.text import CountVectorizer

In [116]:
cv=CountVectorizer()

In [117]:
X_train_cv= cv.fit_transform(X_train.values)

In [118]:
X_train

3533                             Good evening How are you
5204    How come she can get it Should b quite diff to...
808          I am taking half day leave bec i am not well
5432                                Thanx a lot 4 ur help
448                 LOL Have you made plans for new years
                              ...                        
3667                     Thanks for loving me so You rock
4619                          THIS IS A LONG FUCKIN SHOWR
4913    You ve already got a flaky parent It snot supp...
4991                             I m hungry buy smth home
3475    I can probably come by everybody s done around...
Name: Text, Length: 4457, dtype: object

In [119]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

Here , we can see that, this is sparse matrix to narray .its called Bag of Words.




In [120]:
X_train_cv.shape # there are 7676 unique words are locate in our BOW

(4457, 7650)

In [121]:
cv.get_feature_names_out()[2000:2100]

array(['constant', 'constantly', 'contact', 'contacted', 'contacts',
       'contains', 'content', 'contented', 'contention', 'contents',
       'continent', 'continue', 'continued', 'contract', 'contribute',
       'control', 'convenience', 'conversations', 'converted',
       'converter', 'convey', 'convince', 'convinced', 'convincing',
       'cook', 'cooked', 'cookies', 'cooking', 'cool', 'cooped',
       'cooperative', 'copied', 'copies', 'coping', 'cops', 'copy',
       'cornwall', 'corporation', 'correct', 'correction', 'correctly',
       'corrupt', 'corvettes', 'cos', 'cosign', 'cost', 'costa',
       'costing', 'costs', 'costume', 'costumes', 'couch', 'cougar',
       'cough', 'coughing', 'could', 'couldn', 'count', 'countin',
       'country', 'counts', 'coupla', 'couple', 'courage', 'courageous',
       'course', 'court', 'courtroom', 'cousin', 'cover', 'coveragd',
       'covers', 'coz', 'cozy', 'cr01327bt', 'cr9', 'crab', 'crack',
       'craigslist', 'crammed', 'cramps',

In [122]:
#cv.vocabulary_

In [123]:
X_train_np=X_train_cv.toarray()

In [124]:
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [125]:
np.where(X_train_np[0]!=0)

(array([1063, 2668, 3184, 3503, 7613]),)

In [126]:
X_train[:5]

3533                             Good evening How are you
5204    How come she can get it Should b quite diff to...
808          I am taking half day leave bec i am not well
5432                                Thanx a lot 4 ur help
448                 LOL Have you made plans for new years
Name: Text, dtype: object

In [127]:
np.where(X_train_np[2961]!=0)

(array([ 864, 1022, 1098, 1109, 1462, 1617, 2204, 2620, 2814, 3330, 3401,
        3707, 4228, 4371, 4637, 4999, 5833, 6019, 6305, 6766, 6865, 7337,
        7378]),)

In [128]:
X_train_np[2961][1644]

0

In [129]:
#model /classify this model

In [130]:
from sklearn.naive_bayes import MultinomialNB

In [131]:
NB=MultinomialNB()

In [132]:
NB.fit(X_train_cv, y_train)

MultinomialNB()

In [133]:
X_test_cv= cv.transform(X_test)


In [135]:
y_pred=NB.predict(X_test_cv)

In [136]:
from sklearn.metrics import classification_report

In [138]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       977
           1       0.98      0.94      0.96       138

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

